name: crm-prod
services:
  postgres:
    image: postgres:17.9-alpine
    env_file: .env.production
    volumes:
      - production-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    env_file: .env.production

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    env_file: .env.production
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
      - maildev
    restart: always

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

volumes:
  production-db:
